# Generated by Django 3.1.7 on 2021-03-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poop',
            options={'ordering': ['-created_at']},
        ),
    ]
